`define WB_ADDR_SIZE 31:0
`define WB_SEL_ADDR_SIZE 31:12
`define WB_SEL_SIZE 3:0


`define WB_STATE_SIZE 1:0
`define WB_STATE_INACTIVE 2'b00
`define WB_STATE_READ_SINGLE 2'b01
`define WB_STATE_WRITE_SINGLE 2'b10
